### ISSUE TITLE
Inconsistent OHLC,  same ts, different OH values, TS out of range

### ISSUE THREAD

**Issue by jdumont0201** [finnhubio/Finnhub-API#164] opened 2020-04-23 18:03 UTC
## What is the issue ? Plz describe in details
Hi there, 
Reopening an issue over the OHLC accuracy #123 .
On 4h resolution, bars share the same ts (duplicated ts) with various OHLC.
Result also throws dates out of requested range

## How to reproduce the error ?
Requesting OHLC from  Fri, 01 Nov 2019 00:00:00  to  Sun, 01 Dec 2019 23:59:59 +0000
`https://finnhub.io/api/v1/stock/candle?symbol=V&resolution=240&from=1572566400&to=1575244799&token=YOUR_TOKEN`

TS `1575057600` appears twice with different OH values
`{
c: [
184.51,
184.51,
184.51,
166.555
],
h: [
184.83,
184.51,
184.57,
166.555
],
l: [
184.05,
184.51,
184.51,
166.555
],
o: [
184.36,
184.51,
184.57,
166.555
],
s: "ok",
t: [
1575043200,
1575057600,
1575057600,
1587657600
],
v: [
914112,
0,
0,
0
]
}`
## What is the expected result and why do you think it's the correct result ?
1. A single TS appears multiple times on the response, with different data (TS is wrong?)
2. TS 1587657600 was not in the requested range 

Thanks in advance 
JD

**Comment by finnhubio** [comment] 2020-04-23 22:06
Sr for the late reply. I somehow can't reproduce the error at the moment. Here is what I got for t = 
[..., 1575014400,1575028800,1575043200,1575057600]

Hmm, we would probably need more time to investigate your issue.

**Comment by jdumont0201** [comment] 2020-04-24 12:16
I confirm that the output has changed for this request.
I'll keep you informed.

**Comment by finnhubio** [comment] 2020-04-25 02:27
> I confirm that the output has changed for this request.
> 
> Look at this one then
> https://finnhub.io/api/v1/stock/candle?symbol=V&resolution=240&from=1548979200&to=1551657599&token=YOUR_TOKEN
> 
> at the end of it you'll find
> `1551456000, 1551470400, 1551456000, 1551470400` with varying OHLC

The issue should be fixed now. If you still encounter it, plz let us know

**Closed** 2020-04-28 21:47 UTC
